

services:
  appback:
    image: back
    environment:
      DB_USER: postgres
      DB_PASSWORD: Alianza0606
      DB_HOST: db
      APIKEY: ea28a2c3c4bd4fd2b27ef4c80798cc96
    depends_on:
      - db  
    ports:
      - "3001:3001" 

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Alianza0606
      - POSTGRES_USER=postgres
      - POSTGRES_DB=videogames
    ports:
      - "5432:5432"
      
  appfront:
    image: front
    ports:
      - "3000:3000"
    command: ["npm", "start"]

   
