FROM node:16-alpine

ENV NODE_ENV production
LABEL version="1.0"
LABEL description="This is the base docker image for back api videogames."
LABEL maintainer = ["hagiraitorresmacedo@gmail.com"]

WORKDIR /app

COPY package.json  /app

RUN npm install

COPY . /app


EXPOSE 8000

CMD [ "npm", "run", "serve" ]